# Generated by Django 4.0.4 on 2022-09-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_add', models.CharField(max_length=30)),
                ('download_link', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
