# Generated by Django 4.0.4 on 2022-09-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
