# Generated by Django 4.0.4 on 2022-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytf_app', '0002_alter_user_details_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_user_id', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='download_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
